[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlsync = { path = "../../lib/sqlsync" }
simple_logger = "4.1.0"
log = "0.4.14"
anyhow = { version ="1.0.40", features = ["backtrace"] }
bincode = "1.3.3"
serde = { version = "1.0.171", features = ["derive"] }