name = "sqlsync"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

r2_buckets = [
    { binding = "SQLSYNC_REDUCERS", bucket_name = "sqlsync-reducers", preview_bucket_name = "sqlsync-reducers-dev" },
]

[build]
# TODO: this should be --release for production
command = "cargo install -q worker-build && worker-build --dev"

[durable_objects]
bindings = [{ name = "COORDINATOR", class_name = "DocumentCoordinator" }]

[[migrations]]
tag = "2023-08-25"
new_classes = ["DocumentCoordinator"]
