name = "sqlsync"
main = "build/worker/shim.mjs"
compatibility_date = "2023-08-14"
compatibility_flags = ["web_socket_compression"]

r2_buckets = [
    { binding = "SQLSYNC_REDUCERS", bucket_name = "sqlsync-reducers", preview_bucket_name = "sqlsync-reducers-dev" },
]

[build]
# TODO: automatically switch between these two commands based on the environment
# command = "cargo install -q worker-build && worker-build --dev"
command = "cargo install -q worker-build && worker-build"

[durable_objects]
bindings = [{ name = "COORDINATOR", class_name = "DocumentCoordinator" }]

[[migrations]]
tag = "2023-08-25"
new_classes = ["DocumentCoordinator"]
